//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P5WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class nganhdt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nganhdt()
        {
            this.sinh_vien = new HashSet<sinh_vien>();
        }
    
        public string MaNganh { get; set; }
        public string IDBDT { get; set; }
        public string TenNganh { get; set; }
    
        public virtual bacdt bacdt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sinh_vien> sinh_vien { get; set; }
    }
}
