//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P5WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinh_vien
    {
        public string MSSV { get; set; }
        public string MaNganh { get; set; }
        public string MaLop { get; set; }
        public string HoTenSV { get; set; }
        public System.DateTime NgaySinhSV { get; set; }
        public string GioiTinhSV { get; set; }
        public string DiaChiSV { get; set; }
        public string SDT { get; set; }
    
        public virtual nganhdt nganhdt { get; set; }
    }
}
